### PR TITLE
Added Navbar and Footer

### PR DESCRIPTION
**Pull request by Ananyaa03**
Closes Issue: #3 
Features added:
1. Added a navigation bar
2. Added Footer

### CODE REVIEW

**Comment by Ananyaa03** [comment]
Hi, Please add a hacktoberfest or hacktoberfest-accepted label to this issue.

**Comment by intrepidbird** [comment]
Sorry, there is a fix that is needed. It conflicts with some key files.

**Comment by Ananyaa03** [comment]
I have resolved the issue.

**Comment by intrepidbird** [comment]
No, there still seems to be an issue.

Please make sure they are resolved in https://github.com/intrepidbird/graphing-calculator/pull/26/conflicts 👍

**Comment by Ananyaa03** [comment]
I have resolved the conflict.

**Comment by Ananyaa03** [comment]
Hi, can you tell me what the bug is so I can rectify it?

**Comment by intrepidbird** [comment]
The images were too big, and the css was a big messy.

**Comment by Ananyaa03** [comment]
I believe , there must be some issue from my side while i pushed my code. Initially the code was written according to the website. Sorry about that.

**Pull request merged**
