### PR TITLE
Changes : The graph can now update if new equation is entered.

### PR DESCRIPTION
**Pull request by CodeStrate**
• Chart is now destroyed on button click.
• Chart now updates itself with every new equation.
• Reset buttons for both equation and graph added.

- Including other misc. CSS Improvements

### CODE REVIEW

**Comment by CodeStrate** [comment]
@intrepidbird if merged, kindly add the `hacktoberfest` and `hacktoberfest-accepted` labels

**Comment by intrepidbird** [comment]
Please update the code to account for the favicon

**Comment by kclalit64** [comment]
may i work on it?

**Comment by CodeStrate** [comment]
@intrepidbird Accounted for the favicon changes. and some minor improvements
with the buttons.

**Comment by intrepidbird** [comment]
There's still a conflict. Yes, anyone may work on this but I think CodeStrate has almost got it :100: .

**Comment by Uzo-Felix** [comment]
This fix is needed. please resolve

**Comment by CodeStrate** [comment]
@intrepidbird @Uzo-Felix Merged mine and felix's changes. No conflicts as of now.

**Comment by CodeStrate** [comment]
please merge this one first to avoid any more conflicts with other PRs.

**Pull request merged**
